"use client";

import { useState, useTransition } from "react";
import { m } from "framer-motion";
import { deleteBlogPost, saveBlogPost } from "./actions";

type Post = { id: string; title: string; excerpt: string; content: string; cover_image_url: string | null; status: string };
export default function BlogEditor({ post }: { post?: Post }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  return <form action={(data) => startTransition(async () => { const result = await saveBlogPost(data); setMessage("error" in result ? result.error : "Artículo guardado y caché actualizada."); })} encType="multipart/form-data" className="rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur-xl sm:p-6">
    <h2 className="text-lg font-bold text-white">{post ? "Editar artículo" : "Nuevo artículo"}</h2><input type="hidden" name="id" value={post?.id ?? ""} />
    <div className="mt-4 grid gap-3"><input name="title" defaultValue={post?.title} required minLength={5} maxLength={160} placeholder="Título" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white" /><textarea name="excerpt" defaultValue={post?.excerpt} required minLength={20} maxLength={320} rows={2} placeholder="Resumen para tarjetas" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white" /><label className="text-xs text-white/60">Portada (PNG, JPEG o WebP; máximo 5 MB)<input name="cover_image" type="file" accept="image/png,image/jpeg,image/webp" className="mt-1 block w-full rounded-xl border border-dashed border-white/15 bg-black/30 px-3 py-2 text-xs text-white/60" /></label><input name="cover_image_url" defaultValue={post?.cover_image_url ?? ""} type="url" placeholder="O usa una URL pública de portada" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white" /><textarea name="content" defaultValue={post?.content} required minLength={40} maxLength={50000} rows={12} placeholder="Contenido del artículo" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white" /><select name="status" defaultValue={post?.status ?? "draft"} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-white"><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></div>
    <div className="mt-4 flex flex-wrap items-center gap-3"><m.button whileTap={{ scale: 0.98 }} disabled={pending} className="rounded-xl bg-[#D4AF37] px-4 py-2.5 text-xs font-bold text-black disabled:opacity-50">{pending ? "Guardando…" : "Guardar artículo"}</m.button>{post && <m.button type="submit" formAction={(data) => startTransition(async () => { if (!confirm("¿Eliminar este artículo?")) return; const result = await deleteBlogPost(data); setMessage("error" in result ? result.error : "Artículo eliminado."); })} name="id" value={post.id} whileTap={{ scale: 0.98 }} className="rounded-xl border border-red-400/30 px-4 py-2.5 text-xs font-bold text-red-300">Eliminar</m.button>}{message && <p role="status" className="text-xs text-[#48CAE4]">{message}</p>}</div>
  </form>;
}
